import type {
  AnimalListing,
  FeedPost,
  Product,
  ProductCategory,
  Seller,
  ServiceProvider,
  User,
} from "@/types";

export const currentUser: User = {
  id: "u1",
  displayName: "Мария К.",
  avatar: "🐾",
  email: "maria@example.com",
  pets: ["Боня", "Марс"],
  city: "Москва",
};

export const sellers: Seller[] = [
  {
    id: "s1",
    name: "ЗооМир — официальный дилер",
    tier: "certified",
    verifiedAt: "2024-06-12",
    description: "Сертифицированный продавец кормов и аксессуаров",
  },
  {
    id: "s2",
    name: "Лапки & Хвосты",
    tier: "certified",
    verifiedAt: "2025-01-08",
    description: "Премиум-аксессуары для кошек и собак",
  },
  {
    id: "s3",
    name: "Питомник «Северная звезда»",
    tier: "certified",
    verifiedAt: "2023-11-20",
    description: "Породистые щенки и котята с документами РКФ/FIFe",
  },
];

export const productCategories: ProductCategory[] = [
  "Корм",
  "Игрушки",
  "Лежанки",
  "Аптека",
];

export const products: Product[] = [
  {
    id: "p1",
    title: "Корм сухой премиум, 12 кг",
    price: 4890,
    currency: "RUB",
    image: "🦴",
    category: "Корм",
    sellerId: "s1",
    rating: 4.8,
  },
  {
    id: "p2",
    title: "Влажный корм для котят, 24×85 г",
    price: 2190,
    currency: "RUB",
    image: "🐟",
    category: "Корм",
    sellerId: "s1",
    rating: 4.6,
  },
  {
    id: "p3",
    title: "Интерактивная игрушка-мышка",
    price: 890,
    currency: "RUB",
    image: "🐭",
    category: "Игрушки",
    sellerId: "s2",
    rating: 4.9,
  },
  {
    id: "p4",
    title: "Мяч с пищалкой, набор 3 шт.",
    price: 590,
    currency: "RUB",
    image: "⚽",
    category: "Игрушки",
    sellerId: "s2",
    rating: 4.7,
  },
  {
    id: "p5",
    title: "Лежанка ортопедическая L",
    price: 5490,
    currency: "RUB",
    image: "🛏️",
    category: "Лежанки",
    sellerId: "s2",
    rating: 4.8,
  },
  {
    id: "p6",
    title: "Домик-когтеточка «Баобаб»",
    price: 3490,
    currency: "RUB",
    image: "🐱",
    category: "Лежанки",
    sellerId: "s2",
    rating: 4.9,
  },
  {
    id: "p7",
    title: "Витамины для суставов, 60 таб.",
    price: 1290,
    currency: "RUB",
    image: "💊",
    category: "Аптека",
    sellerId: "s1",
    rating: 4.5,
  },
  {
    id: "p8",
    title: "Капли от блох и клещей",
    price: 890,
    currency: "RUB",
    image: "🩹",
    category: "Аптека",
    sellerId: "s1",
    rating: 4.7,
  },
];

export const animals: AnimalListing[] = [
  {
    id: "a1",
    name: "Арчи",
    kind: "dog",
    breed: "Золотистый ретривер",
    age: "3 месяца",
    city: "Москва",
    price: 85000,
    currency: "RUB",
    image: "🐕",
    badges: ["pedigree"],
    description: "Щенок с родословной РКФ, привит, микрочип",
    sellerId: "s3",
  },
  {
    id: "a2",
    name: "Муся",
    kind: "cat",
    breed: "Британская короткошёрстная",
    age: "2 месяца",
    city: "Санкт-Петербург",
    price: 42000,
    currency: "RUB",
    image: "🐈",
    badges: ["pedigree"],
    description: "Котёнок с паспортом FIFe, привит",
    sellerId: "s3",
  },
  {
    id: "a3",
    name: "Барсик",
    kind: "cat",
    age: "1 год",
    city: "Казань",
    image: "😺",
    currency: "RUB",
    badges: ["goodHands"],
    description: "Дружелюбный кот из приюта, ищет любящую семью",
    sellerId: "s3",
  },
  {
    id: "a4",
    name: "Шарик",
    kind: "dog",
    age: "5 лет",
    city: "Новосибирск",
    image: "🐶",
    currency: "RUB",
    badges: ["goodHands"],
    description: "Спокойный пёс, хорошо ладит с детьми",
    sellerId: "s3",
  },
  {
    id: "a5",
    name: "Лаки",
    kind: "dog",
    breed: "Корги",
    age: "4 месяца",
    city: "Москва",
    price: 95000,
    currency: "RUB",
    image: "🦮",
    badges: ["pedigree"],
    description: "Щенок с документами, социализирован",
    sellerId: "s3",
  },
];

export const services: ServiceProvider[] = [
  {
    id: "v1",
    name: "Клиника «ВетЛайф»",
    kind: "veterinary",
    city: "Москва",
    address: "ул. Профсоюзная, 12",
    rating: 4.9,
    reviewCount: 312,
    priceFrom: 1200,
    currency: "RUB",
    image: "🏥",
    specialties: ["Терапия", "Хирургия", "Стоматология"],
    verified: true,
  },
  {
    id: "g1",
    name: "Груминг «Пушистик»",
    kind: "grooming",
    city: "Москва",
    address: "пр-т Мира, 45, стр. 2",
    rating: 4.8,
    reviewCount: 156,
    priceFrom: 2500,
    currency: "RUB",
    image: "✂️",
    specialties: ["Стрижка", "Тримминг", "SPA-уход"],
    verified: true,
  },
  {
    id: "g2",
    name: "Салон «Гладкая шерсть»",
    kind: "grooming",
    city: "Санкт-Петербург",
    address: "Невский пр., 88",
    rating: 4.6,
    reviewCount: 94,
    priceFrom: 1800,
    currency: "RUB",
    image: "🛁",
    specialties: ["Кошки", "Собаки мелких пород"],
    verified: true,
  },
  {
    id: "v2",
    name: "Ветцентр «Здоровый хвост»",
    kind: "veterinary",
    city: "Казань",
    address: "ул. Баумана, 3",
    rating: 4.7,
    reviewCount: 201,
    priceFrom: 900,
    currency: "RUB",
    image: "🩺",
    specialties: ["УЗИ", "Вакцинация", "Стационар"],
    verified: true,
  },
];

export const feedPosts: FeedPost[] = [
  {
    id: "f1",
    authorName: "Анна",
    authorAvatar: "🧑",
    petName: "Боня",
    content:
      "Наконец-то нашли идеальный корм на ЛапМаркет — только у сертифицированных продавцов, спокойно за качество! 🐕",
    image: "📸",
    likes: 42,
    comments: 8,
    createdAt: "2026-05-20T14:30:00",
    tags: ["корм", "собака"],
  },
  {
    id: "f2",
    authorName: "Дмитрий",
    authorAvatar: "👨",
    petName: "Марс",
    content:
      "Записались к грумеру через ЛапМаркет — удобно видеть отзывы и бейдж «Лицензия проверена».",
    likes: 28,
    comments: 3,
    createdAt: "2026-05-19T09:15:00",
    tags: ["груминг", "кот"],
  },
  {
    id: "f3",
    authorName: "Приют «Добрые лапы»",
    authorAvatar: "🏠",
    petName: "Барсик",
    content:
      "Барсик ищет дом! Отметка «в добрые руки» — бесплатно в любящую семью. ❤️",
    image: "🐱",
    likes: 156,
    comments: 24,
    createdAt: "2026-05-18T18:00:00",
    tags: ["приют", "усыновление"],
  },
  {
    id: "f4",
    authorName: "Мария",
    authorAvatar: "👩",
    petName: "Луна",
    content: "Новая лежанка — пушистый рай! Рекомендую раздел «Товары» с галочкой сертификации.",
    image: "🛏️",
    likes: 67,
    comments: 12,
    createdAt: "2026-05-17T11:00:00",
    tags: ["лежанка", "кот"],
  },
];

export function getSeller(id: string): Seller | undefined {
  return sellers.find((s) => s.id === id);
}

export function getCertifiedProducts(): Product[] {
  return products.filter((p) => {
    const seller = getSeller(p.sellerId);
    return seller?.tier === "certified";
  });
}
